---
include:
  - board: seeeduino_xiao_ble
    shield: zmk-config-test_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: seeeduino_xiao_ble
    shield: zmk-config-test_right
